### ISSUE TITLE
Operator precedence: Wait for button release does not work as intended

### ISSUE THREAD

**Issue by JChristensen** [technoblogy/five-leds-puzzle#1]
https://github.com/technoblogy/five-leds-puzzle/blob/b1b3ee8016ac978b866e31141f930374b91f43bf/FiveLEDsPuzzle.ino#L55
Should be:
```c++
  while ((PINB & 0x1F) != 0x1F);      // Wait for all buttons released
```
Cool project, clever code! I may adapt it for a surface-mount ATtiny84A, should be straightforward.

**Comment by technoblogy** [comment]
Thanks! Corrected.

**Comment by technoblogy** [comment]
PS On an ATtiny84 you could extend it to have up to eight buttons and LEDs, using PA0 to PA7, to make a harder puzzle!
